@startuml
Project starts the 26th of november 2017

[meeting with Developers Team] lasts 2 days
[database schema development] lasts 5 days
[user management service] lasts 10 days
[calendar management service] lasts 10 days
[travel planning service] lasts 15 days
[taxi reservation service] lasts 10 days
[mobility sharing reservation service] lasts 10 days
[ticket shop service] lasts 10 days
[notifications delivery service] lasts 5 days
[event notifications service] lasts 5 days
[travel notifications service] lasts 5 days
[integration between services] lasts 10 days

[database schema development] starts at [meeting with Developers Team]'s end
[user management service] starts at [database schema development]'s end
[calendar management service] starts at [user management service]'s end
[travel planning service] starts at [calendar management service]'s end
[taxi reservation service] starts at [travel planning service]'s end
[mobility sharing reservation service] starts at [taxi reservation service]'s end
[ticket shop service] starts at [mobility sharing reservation service]'s end
[notifications delivery service] starts at [ticket shop service]'s end
[event notifications service] starts at [notifications delivery service]'s end
[travel notifications service] starts at [notifications delivery service]'s end
[integration between services] starts at [travel notifications service]'s end

@enduml