@startuml

actor User
participant System

activate User #FFBBBB
User -> System: PersonalArea
activate System #FFBBBB
System -> System: LoadPersonalAreaInformation
System --> User: ShowPersonalAreaPage
deactivate System
User -> System: EditTravelPreferences
activate System #FFBBBB
System -> System: LoadTravelPreferencesInformation
System --> User: ShowEditablePreferencesForm
deactivate System
User -> System: InsertEditatedPreferences
activate System #FFBBBB
System -> System: VerifyData
deactivate System

alt correct data
  System --> User: ShowNewTravelPreferences
else incorrect data
  System --> User: Error
end

@enduml
