@startuml

actor User
participant System
participant ExternalService

note over User: After registration

activate User #FFBBBB
activate System #FFBBBB
System -> User: AskForBillingInformation
deactivate System

alt billing info now
  System --> User: RedirectionMessage
  User -> ExternalService: InsertBillingInformation
  activate ExternalService #FFBBBB
  ExternalService -> ExternalService: VerifyData
  deactivate ExternalService

  alt correct data
    ExternalService -> System: CorrectBillingInformation
    activate System #FFBBBB
    System --> User: NotifyCorrectBillingInfo
    deactivate System
  else incorrect data
    ExternalService -> System: IncorrectBillingInformation
    activate System #FFBBBB
    System --> User: NotifyInvalidBillingInfo
    deactivate System
  end

else billing info later
  System --> User: ConfermationMessage
end

deactivate User

@enduml
