@startuml

actor Guest
participant System
participant ExternalService
actor User

activate Guest #FFBBBB
Guest -> System: Registration
activate System #FFBBBB
System -> System: LoadRegistrationPage
System --> Guest: ShowRegistrationPage
deactivate System #FFBBBB
Guest -> System: InsertInformation
activate System #FFBBBB
System -> System: VerifyInformation
deactivate System #FFBBBB

alt correct information
  System --> Guest: NotifyCorrectInformation
  System -> Guest: sendEmailWithCode
  Guest -> System: insertVerificationCode
  System -> System: verifyCode
  System --> Guest: NotifyCorrectCode
  System -> Guest: SendRedirectionMessage
  Guest -> ExternalService: insertBillingInformation
  activate ExternalService #FFBBBB
  ExternalService -> ExternalService: verifyBillingInformation
  deactivate ExternalService #FFBBBB

  alt correct billing information
    ExternalService -> System: correctBillingInformation
    System -> Guest: acceptingEULA

    alt confirmed
      Guest --> System: sendConfermation
      activate System #FFBBBB
      System -> User: <<createUser>>
      activate User #FFBBBB
      System -> Guest: sendVerificationEmail
      System --> User: showLoginPage
      deactivate System #FFBBBB
      deactivate User #FFBBBB
    else not confirmed
      Guest --> System: sendCancellation
      activate System #FFBBBB
      System -> Guest: errorMessage
      deactivate System #FFBBBB
    end

  else incorrect billing information
    ExternalService -> System: incorrectBillingInformation
    activate ExternalService #FFBBBB
    deactivate ExternalService #FFBBBB
    System -> Guest: notifyInvalidBillingInfo
  end

else incorrect information
  activate System #FFBBBB
  System --> Guest: notifyIncorrectInfo
end

@enduml
