@startuml

actor User
participant System
participant RoutingService
participant SharingService

activate User #FFBBBB
User -> System: NewEvent
activate System #FFBBBB
System -> System: LoadNewEventForm
System --> User: ShowNewEventForm
deactivate System
User -> System: InsertInformation
activate System #FFBBBB
System -> System: VerifyData
deactivate System

alt correct data
  System --> User: DataConfirmation
  User -> System: SuggestedRoutes
  System -> RoutingService: RequestRoutes
  activate RoutingService #FFBBBB
  RoutingService -> System: SentRoutes
  deactivate RoutingService
  System --> User: ShowRoutes

  alt accept sharing
    User -> System: SharingServices
    activate System #FFBBBB
    System -> SharingService: RequestSharingServices
    activate SharingService #FFBBBB
    SharingService -> System: SentSharingAvailableServices
    deactivate SharingService
    System --> User: ShowSharingAvailableServices
    deactivate System
    User -> System: AutoReservation
    activate System #FFBBBB
    System --> User: AutoReservationConfirmation
    deactivate System
    User -> System: SelectSharingServices
    activate System #FFBBBB
    System --> User: SelectedSharingServicesConfirmation
    deactivate System
  else decline sharing
    User -> System: DeclineSharingServices
  end

  User -> System: NewEventConfirm
  System --> User: ShowCreatedEvent
else incorrect data
  System --> User: Error
end

@enduml
