@startuml

actor User
participant WebServer
participant CalendarManagementService
participant DatabaseService

activate User #FFBBBB
User -> WebServer: NewEvent
activate WebServer #FFBBBB
WebServer -> WebServer: LoadNewEventForm
WebServer --> User: ShowNewEventForm
deactivate WebServer
User -> WebServer: InsertInformation
activate WebServer #FFBBBB
WebServer -> CalendarManagementService: EventData
deactivate WebServer
activate CalendarManagementService #FFBBBB
CalendarManagementService -> CalendarManagementService: VerifyData
deactivate CalendarManagementService

alt correct data
  CalendarManagementService -> WebServer: CorrectData
  activate WebServer #FFBBBB
  WebServer --> User: DataConfirmation
  deactivate WebServer
  User -> WebServer: NewEventConfirm
  activate WebServer #FFBBBB
  WebServer -> CalendarManagementService: NewEvent
  activate DatabaseService #FFBBBB
  CalendarManagementService -> DatabaseService: NewEvent
  deactivate DatabaseService
  CalendarManagementService --> WebServer: EventCreated
  WebServer --> User: ShowCreatedEvent
  deactivate WebServer
else incorrect data
  CalendarManagementService -> WebServer: IncorrectData
  activate WebServer #FFBBBB
  WebServer --> User: Error
  deactivate WebServer
end

@enduml
