@startuml

[*] -right-> NewEvent
NewEvent -right-> [*]

NewEvent -up-> AddParticipant
AddParticipant --> AddParticipant
AddParticipant --> NewEvent
NewEvent -up-> AddRecurrencyInformation
AddRecurrencyInformation -> NewEvent
NewEvent --> ScheduleTrip
ScheduleTrip --> ChooseRoute
ChooseRoute --> [*]

    NewEvent: Input basic information (name, place, duration)

    ScheduleTrip: Schedule the trip and check if it's possible\nto be in time given the previous event.\nSee separate detailed statechart.

    ChooseRoute: The user can choose the route he prefer based on the\ntime needed, the cost, the emission of CO2 and if\nhe want to use sharied means

    AddParticipant: For sharing the event with other\npeople (also with user that not\nnecessarily have an account on\nTravlendar+  

    AddRecurrencyInformation: For recurring events (e.g. repeat every monday)

@enduml