@startuml

[*] -right-> NewEvent
NewEvent -right-> [*]
NewEvent: Input basic information (name, place, duration)

NewEvent --> AddParticipant
AddParticipant --> AddParticipant
AddParticipant --> NewEvent

NewEvent -down-> AddRecurrencyInformation
state AddRecurrencyInformation: For recurring events (e.g. repeat every monday)
AddRecurrencyInformation -> NewEvent

NewEvent -right-> ScheduleTrip
ScheduleTrip -right-> [*]

state ScheduleTrip {
    ScheduleTrip: Schedule the trip and check if it's possible\n\
    to be in time given the previous event. \n\
    See separate detailed statechart.
}

@enduml