@startuml

[*] --> SignUp
SignUp --> SignUp: Email \nalready \nuse
SignUp --> EmailVerification
EmailVerification --> EULAAccepting
EULAAccepting --> [*]:  New user \n registered
EULAAccepting --> BillingInformation: optionally
BillingInformation --> [*]: New user \n registered
SignUp: Enter basical personal information \n(email, password)
EmailVerification: Entrer in the box the code recived via email
EULAAccepting: Read carefully EULA and accept the general condition
BillingInformation: Enter the billing information
@enduml